{ pkgs, ... }:
{
  home.packages = with pkgs; [
    unstable.sublime-merge-dev
    unstable.android-studio
    unstable.windsurf
    unstable.shotcut
    unstable.slack
    unstable.discord
    unstable.google-chrome
    unstable.telegram-desktop
    unstable.vscode

    file
    pciutils
    fastfetch
    wl-clipboard
    gnome-tweaks
    nixfmt-tree
    dconf-editor
    dconf2nix
    qbittorrent
    vlc
    ripgrep
    evtest
    bat
    tree
    bustle
    wev
    gimp
    openvpn
    nixfmt
    nil
    sensible-utils
    libreoffice
    gucharmap
    obsidian
    inkscape
    godotPackages_4_5.godot
    firefox
    blender
    pdfarranger
    gnome-boxes
    glab
    prismlauncher
    liberation_ttf
    vista-fonts
    meld
    git-crypt
    icon-library
    typst
    typstyle
    tinymist
    ffmpeg
    zulu25
    nodejs
    sox # required by Claude's /voice command
    eyedropper
  ];
}
